kind: pipeline
name: default

steps:
- name: StaticCheck
  image: neszt/cppcheck-docker
  commands:
  - cppcheck --check-config --enable=all .

- name: StyleCheck
  image: jlarfors/libgit2-cpplint
  commands:
    - cpplint *

- name: test
  image: m1kev4ndyke/docker-gtest
  commands:
  - make test

- name: build & run
  image: m1kev4ndyke/docker-gtest
  commands:
  - make run


